### ISSUE TITLE
Switching from zimme -> collectionbehaviour

### ISSUE THREAD

**Issue by kwuite** [meteor-collectionbehaviours/softremove#1]
Hi Zimme,

I am replacing your timestamp and softremovable packages since I have been upgrading to collection2-core, autform and node-simpl-schema. I would love to keep on using your packages and so I found this repo, but without documentation.

Will you be releasing an update anytime soon and can you give me some info on how to switch from the old versus the new collectionbehaviour strategy?

Thanks in advance

**Comment by zimme** [comment]
Hey,

While doing the work on the new versions of the packages I ran into some problems with collection-hooks which I was relying on. I've published a release candidate of collection-hooks that took care of some issues but I started experimenting with the possibility to not use collection-hooks and time got away from me and I haven't had time to work on this in a while.

I do intend on continuing working on this but I do not know when I have the time and that's why I put this under it's own organization so that it will be better suited to become a true community project.

The intended way of using this new version is something like this.
```js
import { Mongo } from "meteor/mongo";
import { softremove } from "meteor/collectionbehaviours:softremove";

const Posts = new Mongo.Collection("posts");

softremove(Posts, {
  removedAt: "deletedAt",
});

export { Posts };
```
This way I don't extend `Mongo` with `attachBehaviour` as in previous versions.
I've also look into see if I can simplify the logic of this package to do "less" i.e. don't
change the behaviour of `update` to handle the update of `removed` properties differently.

The problem with this was that I need access to the current userId on the server and this will now soon be possible in a consise way with a patch I've made to Meteor's DDP and accounts packages.

**Comment by kwuite** [comment]
Dear Zimme,

Thank you for your swift and foremost extensive reply to my inquiry.

Since I have taken over development from another programmer (and I just switched from Python to Node, so sorry if the questions are junior) I presumed the original softremove implementation worked (with zimme:collection-softremovable), but guess what It did not.

We still use blaze (yes I know) with autoform and in order to remove an Object from a schema, the package aldeed:meteor-delete-button was used: 

```
            {{#quickRemoveButton collection=collection _id=dishId class="button button--delete" onSuccess=onDelete}}
              {{__ 'dish.form.delete'}}
            {{/quickRemoveButton}}
```

Also the former developer used this code to permit the call:

```
Collection.permit('softRemove')
  .ifLoggedIn()
```

While looking at the [delete button repo](https://github.com/aldeed/meteor-delete-button/blob/master/delete-button.js) it must be the problem that this code is not initiating your hook:

```
beforeRemove.call({
      remove: function () {
        collection.remove(self._id, function (error, result) {
          if (error) {
            onError(error);
          } else {
            onSuccess(result);
          }
});
```

I promise it shall be the last question ;). But can you point me in the right direction to ensure the permit call works and that the softremove hook is initiated after removal?

**Comment by kwuite** [comment]
Dear Zimme,

Your package works fine. I got it covered by forking the delete-button package and writing my own removal types. Added collection.softRemove as type and everything works perfectly now.

Thank you for your time.

Sine Cera,
Kelvin

**Comment by zimme** [comment]
Awesome! :+1:
